name: What's On

on:
  workflow_dispatch: # enables triggering from the website
  push:
    branches:
      - main
    paths:
      - index.md

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checks out repository
      - uses: actions/setup-python@v3 # sets up python env
        with:
          python-version: 3.x
      - run: pip install pyyaml
      - name: Update index.md
        run: whats-on/update-index.py
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.md
          git commit -m "Auto-update schedule"
          git push
  create-discord-events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: pip install pyyaml
      - name: Create Discord events
        run: whats-on/create-discord-events.py
  update-data-stores:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: pip install pyyaml
      - name: Update data store
        run: whats-on/update-data-store.py